---
title: "R Notebook"
output: html_notebook
---



```{r message=F}
library(data.table)
library(readr)
library(dplyr)
library(knitr)
library(kableExtra)
library(Seurat)

seurobj <- readRDS('output/seurat_objects/180831/10x-180831')
gene_annotations <- fread('tables/tables_paper/all_tables/genes_biomart.txt', sep='\t', quote="", header=T)
```


```{r}
ids2symbols <- read.table('tables/tables_paper/all_tables/10x-180831-geneids-genesymbols.tsv', header=T)
```


#BEAM clusters

```{r}
combined <- list()

for (i in 1:6){
  beam_genelist <- read.table(paste('tables/tables_paper/all_tables/BEAM/heatmap_logFC0.3_ncluster6/genelist_cluster', i, '.tsv', sep=''), sep='\t', header=T)
  beam_genelist['ensembl_gene_id'] <- ids2symbols$ensembl_gene_id[match(beam_genelist$gene_short_name, ids2symbols$gene_symbol)]
  beam_genelist['cluster'] <- i
  
  #add geneinfo
  merged <- merge(beam_genelist, gene_annotations[,c('Gene stable ID', 'Gene type', 'GO term accession', 'GO term name')], by.y='Gene stable ID', by.x='ensembl_gene_id')
  
  #filter for tf's and gene type != protein coding
  filtered <- merged[c(which(c(merged$`GO term name`) %like% 'transcription factor'),
                     which(merged$`GO term definition` %like% 'transcription factor'),
                     which(merged$`Gene type` != 'protein_coding')),]
  
  #filter out duplicate genes
  filtered <- filtered[!duplicated(filtered$gene_short_name),]
  
  combined[[i]] <- filtered
}

combined <- do.call("rbind", combined)
```

```{r}
kable(combined[c('gene_short_name', 'qval', 'avgLogFC_State2_State3', 'cluster', 'Gene type', 'GO term accession', 'GO term name')]) %>%
  kable_styling(bootstrap_options = "striped")
```


```{r}
#write.table(combined, file='../tables/tables_paper/all_tables/BEAM/heatmap_logFC0.3_ncluster6/genelist_TFs.tsv', sep='\t', quote=F, row.names=F)
#write.table(combined, file='../tables/tables_paper/supplementary_tables/BEAM_logFC0.3_nclusters6/genelist_TFs.tsv', sep='\t', quote=F, row.names=F)
```

```{r}
combined_upper_branch <- combined[combined$avgLogFC_State2_State3 > 0,]
combined_lower_branch <- combined[combined$avgLogFC_State2_State3 < 0,]
```

```{r fig.show='hide', message=F}
plots_upper <- FeaturePlot(seurobj, features.plot=as.vector(combined_upper_branch$gene_short_name), nCol=4, cols.use=c('gray', 'blue'), no.legend=F, no.axes=T, do.return=T)

plots_upper_edited <- list()

for (p in names(plots_upper)){
  plots_upper_edited[[p]] <- plots_upper[[p]] + scale_color_gradient(name='Expr.', low='gray', high='blue', guide='colorbar') + theme(legend.title=element_text(size=9), legend.text=element_text(size=9), legend.key.height = unit(0.6, 'cm'), legend.key.width=unit(0.2, 'cm'))
}
grid_upper <- plot_grid(plotlist=plots_upper_edited, ncol=4)
```


```{r fig.height = 10, fig.width = 12, fig.align = "center"}
grid_upper
#save_plot('figures/figures_paper/supplementary_figures/10_tf-analysis/TFs_upper_branch.pdf', grid_upper, base_height=9.14, base_width=12)
#save_plot('figures/figures_paper/supplementary_figures/10_tf-analysis/TFs_upper_branch.png', grid_upper, base_height=9.14, base_width=12)
```

```{r fig.show='hide', message=F}
plots_lower <- FeaturePlot(seurobj, features.plot=as.vector(combined_lower_branch$gene_short_name), nCol=3, cols.use=c('gray', 'blue'), no.legend=F, no.axes=T, do.return=T)

plots_lower_edited <- list()

for (p in names(plots_lower)){
  plots_lower_edited[[p]] <- plots_lower[[p]] + scale_color_gradient(name='Expr.', low='gray', high='blue', guide='colorbar') + theme(legend.title=element_text(size=9), legend.text=element_text(size=9), legend.key.height = unit(0.6, 'cm'), legend.key.width=unit(0.2, 'cm'))
}
grid_lower <- plot_grid(plotlist=plots_lower_edited, ncol=4)
```

```{r, fig.height = 15, fig.width = 12, fig.align = "center"}
grid_lower
#save_plot('figures/figures_paper/supplementary_figures/10_tf-analysis/TFs_lower_branch.pdf', grid_lower, base_height=16, base_width=12)
#save_plot('figures/figures_paper/supplementary_figures/10_tf-analysis/TFs_lower_branch.png', grid_lower, base_height=16, base_width=12)
```

