---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

Plots of 10x-180504 before quality control.

Loading libraries and datasets. 

```{r results='hide', message=FALSE, warning=FALSE}
library(Seurat)
library(dplyr)

all10x.beforeqc <- readRDS('output/10x-180504-beforeQC')
all10x <- readRDS('output/10x-180504')
```

```{r}
pm <- VlnPlot(all10x.beforeqc, features.plot='percent.mito', group.by='sample_name', point.size.use = -1, do.return=T, x.lab.rot=T, size.x.use=8) + geom_hline(yintercept=0.08, linetype="dashed", color = "red")
pm
```

```{r}
numi <- VlnPlot(all10x.beforeqc, features.plot='nUMI', group.by='sample_name', point.size.use = -1, do.return=T, x.lab.rot=T, size.x.use=8) + geom_hline(yintercept=110000, linetype="dashed", color = "red")
numi
```

```{r}
ngene <- VlnPlot(all10x.beforeqc, features.plot='nGene', group.by='sample_name', point.size.use = -1, do.return=T, x.lab.rot=T, size.x.use=8) + geom_hline(yintercept=200, linetype="dashed", color = "red") + geom_hline(yintercept=9000, linetype="dashed", color = "red")
ngene
```

```{r}
GenePlot(all10x.beforeqc, 'nUMI', 'nGene', cex.use = 0.2, do.return=T)
```

Number of cells before and after QC

```{r}
before <- all10x.beforeqc@meta.data %>% count(sample_name)
after <- all10x@meta.data %>% count(sample_name)
ncells <- merge(before, after, by='sample_name', suffixes=c('.before', '.after'))
ncells
```

```{r}
write.table(ncells, file='tables/10x-180504-nCells.txt', sep='\t', row.names = F, quote=F)
```


#Figures for report

```{r fig1, fig.height = 3, fig.width = 12, fig.align = "center"}
sfig <- plot_grid(
  pm,
  numi,
  ngene,
  labels="auto", nrow=1
)
save_plot("plots/supplementary_figures/sfig_180504_qcplots.pdf", sfig, base_width=12, base_height=3)
sfig
```

