---
title: "R Notebook"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: 
      smooth_scroll: true
---


```{r}
library(GOplot)
```



```{r}
name <- 'heatmap_logFC0.3_ncluster6'
folder <- paste('tables/BEAM/', name, sep='')
gsea_files <- list.files(paste(folder, '/REVIGO_cleaned/', sep=''))

clusters <- c(1,2,3,4,6)

gsea <- list()
genelist <- list()

for (i in clusters){
  gsea_cluster <- read.table(paste(folder, '/REVIGO_cleaned/', 'REVIGO_cluster', i, '_cleaned.tsv', sep=''), header=T)
  gsea_cluster['cluster'] <- i
  genes_cluster <- read.table(paste(folder, '/genelist_cluster', i, '.tsv', sep=''))
  gsea[[i]] <- gsea_cluster
  genelist[[i]] <- genes_cluster
}

gsea <- do.call("rbind", gsea)
genelist <- do.call("rbind", genelist)
```

```{r}
create_terms <- function(gsea){
  return(data.frame(category=gsea$gsea.domain, ID=gsea$revigo.term_ID, term=gsea$revigo.description, adj_pval=gsea$gsea.p.value, genes=gsea$gsea.intersection, cluster=gsea$cluster))
}

create_genes <- function(genelist){
  return(data.frame(ID=genelist$gene_short_name, logFC=genelist$avgLogFC_State2_State3))
}
```

#All terms

```{r}
terms <- create_terms(gsea)
genes <- create_genes(genelist)
circ <- circle_dat(terms, genes)
```

```{r, fig.height = 10, fig.width = 20, fig.align = "center"}
GOBar(circ)
```

```{r, fig.height = 12, fig.width = 20, fig.align = "center"}
GOBubble(circ, labels=8, ID=F)
```

```{r, fig.height = 12, fig.width = 20, fig.align = "center"}
GOBubble(circ, labels=8, ID=F, display='mutliple')
```

#Terms associated with metabolic branch

Cluster 2 and 6 (up in metabolic branch) and cluster 4 (down in metabolic branch).

```{r}
gsea_filtered_metabolic <- gsea[gsea$cluster %in% c(2,6,4),]
terms_metabolic <- create_terms(gsea_filtered_metabolic)
#genes <- rbind(genes_c2_swapped, genes_c5_swapped, genes_c4_swapped)
circ_metabolic <- circle_dat(terms_metabolic, genes)
```


```{r, fig.height = 10, fig.width = 20, fig.align = "center"}
GOBar(circ_metabolic)
```

```{r, fig.height = 12, fig.width = 20, fig.align = "center"}
GOBubble(circ_metabolic, labels=8, ID=F)
```

```{r, fig.height = 12, fig.width = 20, fig.align = "center"}
GOBubble(circ_metabolic, labels=8, ID=F, display='mutliple')
```

#Terms associated with ECM branch

Cluster 1 (down in ECM branch) and cluster 3 (up in ECM branch)

```{r}
gsea_filtered_ecm <- gsea[gsea$cluster %in% c(1,3),]
terms_ecm <- create_terms(gsea_filtered_ecm)
genes_swapped <- data.frame(ID=genes$ID, logFC=genes$logFC*-1) #swap fold change direction
circ_ecm <- circle_dat(terms_ecm, genes_swapped)
```

```{r, fig.height = 10, fig.width = 20, fig.align = "center"}
GOBar(circ_ecm)
```

```{r, fig.height = 12, fig.width = 20, fig.align = "center"}
GOBubble(circ_ecm, labels=2, ID=F)
```

```{r, fig.height = 12, fig.width = 20, fig.align = "center"}
GOBubble(circ_ecm, labels=2, ID=F, display='mutliple')
```

#Only upregulated terms

```{r}
gsea_upregulated <- gsea[gsea$cluster %in% c(2,6,3),]
terms_upregulated <- create_terms(gsea_upregulated)
circ_upregulated <- circle_dat(terms_upregulated, genes)
```

```{r, fig.height = 10, fig.width = 20, fig.align = "center"}
GOBar(circ_upregulated)
```

Negative Z-score = terms upregulated in ECM branch. Positive Z-score = terms upregulated in metabolic branch.

```{r, fig.height = 12, fig.width = 20, fig.align = "center"}
GOBubble(circ_upregulated, labels=2, ID=F)
```

```{r, fig.height = 12, fig.width = 20, fig.align = "center"}
GOBubble(circ_upregulated, labels=8, ID=F, display='mutliple')
```
