---
title: "R Notebook"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: 
      smooth_scroll: true
---


```{r}
library(Seurat)
#all10x <- readRDS('../output/10x-180504')
#markers_depots <- read.table('../output/markergenes/180504/DEPOT_MARKERS')
#markers_samples <- read.table('../output/markergenes/180504/DEPOT_MARKERS_SAMPLE_INTERSECT')
```



```{r}

```


#Figures for report

```{r fig1, fig.height = 15, fig.width = 6, fig.align = "center"}
#Brown: TM4SF1, LY6K, HOXB7
#Visceral: BARX1, LINC01116
fig1 <- plot_grid(
  VlnPlot(all10x, features.plot='TM4SF1', point.size.use = -1, group.by='sample_name', x.lab.rot=T, size.x.use = 8),
  VlnPlot(all10x, features.plot='LY6K', point.size.use = -1, group.by='sample_name', x.lab.rot=T, size.x.use = 8),
  VlnPlot(all10x, features.plot='HOXB7', point.size.use = -1, group.by='sample_name', x.lab.rot=T, size.x.use = 8),
  VlnPlot(all10x, features.plot='BARX1', point.size.use = -1, group.by='sample_name', x.lab.rot=T, size.x.use = 8),
  VlnPlot(all10x, features.plot='LINC01116', point.size.use = -1, group.by='sample_name', x.lab.rot=T, size.x.use = 8),
  labels='auto', ncol=1
)

save_plot("plots/180504_depot_markers.pdf", fig1, base_width=6, base_height=15)
```

