---
title: "R Notebook"
output: html_notebook
---

```{r results='hide', message=FALSE, warning=FALSE}
library(Seurat)
data <- readRDS('output/10x-180831-notcleaned')
```

TSNE plots of the data.

```{r}
t1 <- TSNEPlot(data, group.by='timepoint', pt.size=0.1)
```

```{r}
t2 <- TSNEPlot(data, group.by='Phase', pt.size=0.1)
```

```{r}
t3 <- FeaturePlot(data, features.plot=c('nGene'), cols.use=c('gray', 'blue'), no.legend = F)
```

```{r}
#t4 <- DimPlot(data, reduction.use='tsne', cells.highlight = rownames(data@meta.data)[data@meta.data$res.0.5 == 1], cols.highlight = 'blue', cols.use='gray')
```


```{r}
TSNEPlot(data, group.by='res.0.5', pt.size=0.1, do.label=T)
```

Remove bad quality cluster 1 from the data.

```{r}
data_cleaned <- SubsetData(data, cells.use=rownames(data@meta.data)[data@meta.data$res.0.5 != 1])
```

```{r}
TSNEPlot(data_cleaned, group.by='res.0.5', pt.size=0.1)
```

Save the cleaned up Seurat object to run preprocessing again (new PCA, clustering and tSNE).

```{r}
#saveRDS(data_cleaned, 'output/10x-180831')
```

Save the data with the bad quality cluster in case it is needed for other plots.

```{r}
#saveRDS(data, 'output/10x-180831-notcleaned')
```

#Figures for report

```{r fig1, fig.height = 9, fig.width = 12, fig.align = "center"}
#sfig <- plot_grid(
#  t4,
#  t1,
#  t2,
#  t3,
#  nrow=2, labels='auto'
#)
#save_plot('plots/supplementary_figures/sfig_180831_bad-quality-cluster.pdf', sfig, base_width=12, base_height = 9)
#sfig
```

