---
title: "R Notebook"
output: html_notebook
---


```{r}
library(Seurat)
library(cowplot)
library(dplyr)
library(tidyr)
```

```{r}
wolfrum <- readRDS('/projects/timshel/sc-scheele_lab_adipose_fluidigm_c1/data-wolfrum/wolfrum.compute.seurat_obj.rds')
```

```{r fig.height = 5, fig.width = 12, fig.align = "center"}
plot_grid(
  UMAPPlot(wolfrum, group.by='orig.ident', label=T),
  UMAPPlot(wolfrum, group.by='seurat_clusters', label=T)
)
```

What do the clusters represent?

```{r}
markers <- read.table('/projects/pytrik/sc_adipose/analyze_10x_fluidigm/10x-adipocyte-analysis/output/markergenes/wolfrum/markers_wolfrum.compute.seurat_obj.rds_seurat_clusters_negbinom', sep='\t', header=T)
```

```{r}
pos_markers_top10 <- markers %>% 
  group_by(cluster) %>% 
  top_n(n=10, wt=avg_logFC) 
  #unite(col='cluster_gene', c(cluster, gene), remove=F)
  
neg_markers_top10 <- markers %>% 
  group_by(cluster) %>% 
  top_n(n=10, wt=desc(avg_logFC))

pos_markers_top10
```







```{r}
plot_featuresplots <- function(df, features){
  plots <- FeaturePlot(df, features=features, combine = FALSE, pt.size=1)
  for(i in 1:length(plots)) {
    plots[[i]] <- plots[[i]] + NoAxes()
  }
  plot_grid(plotlist=plots, ncol=2)
}
```

```{r fig.height = 10, fig.width = 10, fig.align = "center"}
plot_featureplots(wolfrum, features=pos_markers_top20[pos_markers_top20$cluster == 0]$gene)
```


```{r, fig.show='hide', results='hide', message=F}

```

```{r, fig.height = 112, fig.width = 10, fig.align = "center"}
#height 1 row = 3. 
#27 clusters. 27*10=270 plots. height=270*3=810
plot_grid(plotlist=plots, ncol=3)
```

```{r, fig.show='hide', results='hide', message=F}
plots <- FeaturePlot(wolfrum, features=as.vector(neg_markers_top20$gene), combine = FALSE, pt.size=1)

for(i in 1:length(plots)) {
  plots[[i]] <- plots[[i]] + ggtitle(neg_markers_top20$cluster_gene[i]) + NoAxes()
}
```


```{r, fig.height = 112, fig.width = 10, fig.align = "center"}
plot_grid(plotlist=plots, ncol=3)
```


