---
title: "R Notebook"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float: 
      smooth_scroll: true
---

```{r}
library(Seurat)
library(scmap)
library(SingleCellExperiment)
library(dplyr)
```

Data loading.

```{r}
data_180831 <- readRDS('/projects/pytrik/sc_adipose/analyze_10x_fluidigm/10x-adipocyte-analysis/output/seurat_objects/180831/10x-180831-S3')
sce_180831 <- as.SingleCellExperiment(data_180831)
wolfrum <- readRDS('/projects/pytrik/sc_adipose/analyze_10x_fluidigm/10x-adipocyte-analysis/output/seurat_objects/wolfrum/wolfrum.compute.seurat_obj.rds')
sce_wolfrum <- as.SingleCellExperiment(wolfrum)
```

Select features

```{r}
rowData(sce_180831)['feature_symbol'] <- rownames(sce_180831)
rowData(sce_wolfrum)['feature_symbol'] <- rownames(sce_wolfrum)

counts(sce_180831) <- as.matrix(counts(sce_180831))
logcounts(sce_180831) <- as.matrix(logcounts(sce_180831))

counts(sce_wolfrum) <- as.matrix(counts(sce_wolfrum))
logcounts(sce_wolfrum) <- as.matrix(logcounts(sce_wolfrum))

sce_180831 <- selectFeatures(sce_180831, suppress_plot = FALSE)
```

Setting the right column for clustering

```{r}
sce_180831 <- indexCluster(sce_180831, cluster_col = 'branch')
```


```{r}
scmapCluster_results <- scmapCluster(
  projection = sce_wolfrum, 
  index_list = list(
    sce_maca_fat = metadata(sce_180831)$scmap_cluster_index
  ),
  threshold=0.5  #default=0.7 
)
```

```{r}
pred <- as.data.frame(table(scmapCluster_results$scmap_cluster_labs))
pred <- pred[order(-pred$Freq),]
pred
```

```{r}
predicted_labels <- as.data.frame(
    row.names=rownames(sce_wolfrum@colData), 
    x=as.vector(scmapCluster_results$scmap_cluster_labs))
names(predicted_labels) <- 'predicted_labels_scmap'
wolfrum <- AddMetaData(wolfrum, metadata=predicted_labels, col.name='predicted_labels_scmap')
UMAPPlot(wolfrum, group.by='predicted_labels_scmap', pt.size=0.1)
```

On the subset

```{r}
wolfrum_subset <- readRDS('/projects/pytrik/sc_adipose/analyze_10x_fluidigm/10x-adipocyte-analysis/output/seurat_objects/wolfrum/wolfrum_subset.compute.seurat_obj.rds')
sce_wolfrum_subset <- as.SingleCellExperiment(wolfrum_subset)
```


```{r}
rowData(sce_wolfrum_subset)['feature_symbol'] <- rownames(sce_wolfrum_subset)

counts(sce_wolfrum_subset) <- as.matrix(counts(sce_wolfrum_subset))
logcounts(sce_wolfrum_subset) <- as.matrix(logcounts(sce_wolfrum_subset))

sce_wolfrum_subset <- selectFeatures(sce_wolfrum_subset, suppress_plot = FALSE)

scmapCluster_results_subset <- scmapCluster(
  projection = sce_wolfrum_subset, 
  index_list = list(
    sce_maca_fat = metadata(sce_180831)$scmap_cluster_index
  ),
  threshold=0.4  #default=0.7 
)

pred <- as.data.frame(table(scmapCluster_results_subset$scmap_cluster_labs))
pred <- pred[order(-pred$Freq),]
pred

```

```{r}
predicted_labels <- as.data.frame(
    row.names=rownames(sce_wolfrum_subset@colData), 
    x=as.vector(scmapCluster_results_subset$scmap_cluster_labs))
names(predicted_labels) <- 'predicted_labels_scmap'
wolfrum <- AddMetaData(wolfrum_subset, metadata=predicted_labels, col.name='predicted_labels_scmap')
UMAPPlot(wolfrum, group.by='predicted_labels_scmap', pt.size=0.1)
```

