---
title: "R Notebook"
output: html_notebook
---


```{r}
library(Seurat)
library(cowplot)
library(dplyr)
library(tidyr)
```

```{r}
wolfrum <- readRDS('/projects/timshel/sc-scheele_lab_adipose_fluidigm_c1/data-wolfrum/wolfrum.compute.seurat_obj.rds')
```

```{r fig.height = 6, fig.width = 12, fig.align = "center"}
plot_grid(
  UMAPPlot(wolfrum, group.by='orig.ident', label=T),
  UMAPPlot(wolfrum, group.by='seurat_clusters', label=T)
)
```

What do the clusters represent?

```{r}
markers <- read.table('../output/markergenes/wolfrum/markers_wolfrum.compute.seurat_obj.rds_seurat_clusters_negbinom', sep='\t', header=T)
```

```{r}
pos_markers_top20 <- markers %>% 
  group_by(cluster) %>% 
  top_n(n=6, wt=avg_logFC) %>% 
  unite(col='cluster_gene', c(cluster, gene), remove=F)
  
neg_markers_top20 <- markers %>% 
  group_by(cluster) %>% 
  top_n(n=6, wt=desc(avg_logFC)) %>%
  unite(col='cluster_gene', c(cluster, gene), remove=F)
```

```{r, fig.show='hide', results='hide', message=F}
plots <- FeaturePlot(wolfrum, features=as.vector(pos_markers_top20$gene[1:6]), combine = FALSE, pt.size=1)

for(i in 1:length(plots)) {
  plots[[i]] <- plots[[i]] + ggtitle(pos_markers_top20$cluster_gene[i]) + NoAxes()
}
```

```{r, fig.height = 112, fig.width = 10, fig.align = "center"}
#height 1 row = 3. 
#27 clusters. 27*2 = 54 rows. height = 54*3 = 112 
plot_grid(plotlist=plots, ncol=3)
```

U and L branch markers. 

```{r fig.height = 30, fig.width = 9, fig.align = "center"}
FeaturePlot(wolfrum, features=c('UCP2', 'FABP5', 'G0S2', 'FABP4', 'ADIPOQ', 'ADIRF', 'CD36', 'PLIN4', 'APOD', 'MGP', 'DCN', 'CTGF', 'IGF2', 'CCDC80', 'PLAC9', 'THBS1'), cols=c('gray', 'blue'), ncol = 2, reduction='umap', pt.size=1)
```

Preadipocytes

```{r fig.height = 30, fig.width = 12, fig.align = "center"}
FeaturePlot(wolfrum, features=c('TMSB4X'), cols=c('gray', 'blue'), ncol = 2, reduction='umap', pt.size=1)
```

#Monocle

Ran Monocle on the Wolfrum subset with the same gene list that was used to build the 10x-180831 trajectory. 

```{r}
monocle_results <- readRDS('../output/monocle/wolfrum/wolfrum_subset.compute.seurat_obj.rds-monocle-monocle_genelist_T1T2T3_T4T5_res.1.5')

```

```{r}
plot_grid(
  plot_cell_trajectory(monocle_results, color_by='State'),
  plot_cell_trajectory(monocle_results, color_by='pred.branch.id')
)
```

```{r}
wolfrum_subset <- AddMetaData(wolfrum_subset, pData(monocle_results)['State'])
```


```{r}
get_ratios <- function(data, col1, col2){
  states <- unique(data@meta.data[,col1])
  values <- unique(data@meta.data[,col2])
  df <- as.data.frame(matrix(ncol=length(values)+1, nrow=length(states)))
  colnames(df) <- c('n', values)
  rownames(df) <- states
  for (state in states){
    n_state = length(which(data@meta.data[col1] == state))
    df[state, 'n'] <- n_state
    for (value in values){
    	n_state_value <- length(which(data@meta.data[col1] == state & data@meta.data[col2] == value))
	    perc_state_value <- n_state_value / n_state
	    df[state, value] <- round(perc_state_value, 2)
    }
  }
  return(df)
}
```

```{r}
states.prediction <- get_ratios(data=wolfrum_subset, col1='State', col2='pred.branch.id')
states.prediction
```

```{r}

```


